"""updated error

Revision ID: 4c4213eb5c43
Revises: ed7266a6dcf6
Create Date: 2024-03-21 16:29:58.481315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c4213eb5c43'
down_revision = 'ed7266a6dcf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('saving_target', sa.Float(), nullable=False),
    sa.Column('start_timeframe', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('end_timeframe', sa.DateTime(), nullable=True),
    sa.Column('emoji', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_personal_goals_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personal_goals'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal_goals')
    # ### end Alembic commands ###
